In [1]:
## Load 3 datasets
import pandas as pd

# Load datasets
load_df = pd.read_csv("Electric_Load_Data_Train.csv")
weather_df = pd.read_csv("External_Factor_Data_Train.csv")
events_df = pd.read_csv("Events_Data.csv")

# Check first 5 rows of each
print("Load Data:")
display(load_df.head())

print("Weather Data:")
display(weather_df.head())

print("Events Data:")
display(events_df.head())

Load Data:

             DATETIME    LOAD
0  01APR2013:00:15:00  1136.0
1  01APR2013:00:30:00  1111.0
2  01APR2013:00:45:00  1081.0
3  01APR2013:01:00:00  1050.0
4  01APR2013:01:15:00  1023.0

Weather Data:

,DATETIME,ACT_HEAT_INDEX,ACT_HUMIDITY,ACT_RAIN,ACT_TEMP,COOL_FACTOR
0,01APR2013:00:15:00,26.289972,67.65,0.0,25.88,0.0
1,01APR2013:00:30:00,26.145567,68.86,0.0,25.72,0.0
2,01APR2013:00:45:00,26.048589,69.78,0.0,25.61,0.0
3,01APR2013:01:00:00,25.938489,71.04,0.0,25.48,0.0
4,01APR2013:01:15:00,25.891289,71.76,0.0,25.42,0.0

Events Data:

        Date                          Event_Name  Holiday_Ind Remarks
0  01-Jan-11                      New Year's Day            1     NaN
1  15-Jan-11                     Makar Sankranti            1     NaN
2  26-Jan-11                        Republic Day            1     NaN
3  16-Feb-11                          Id-e-Milad            1     NaN
4  19-Feb-11  Chatrapati Shivaji Maharaj Jayanti            1     NaN

In [2]:
## Check shapes
print(load_df.shape)
print(weather_df.shape)
print(events_df.shape)

(283391, 2)
(283391, 6)
(645, 4)

In [3]:
## Converting Datetime to standard format

load_df["DATETIME"] = pd.to_datetime(
    load_df["DATETIME"],
    format="%d%b%Y:%H:%M:%S"
)

In [4]:
load_df.dtypes

DATETIME    datetime64[ns]
LOAD               float64
dtype: object

In [5]:
## Converting Datetime to standard format

weather_df["DATETIME"] = pd.to_datetime(
    weather_df["DATETIME"],
    format="%d%b%Y:%H:%M:%S"
)

weather_df.dtypes

DATETIME          datetime64[ns]
ACT_HEAT_INDEX           float64
ACT_HUMIDITY             float64
ACT_RAIN                 float64
ACT_TEMP                 float64
COOL_FACTOR              float64
dtype: object

In [6]:
## Converting Datetime to standard format

import re
import pandas as pd

def extract_first_date(text):
    if pd.isna(text):
        return None
    
    # Remove ordinal suffixes (st, nd, rd, th)
    text = re.sub(r'(\d+)(st|nd|rd|th)', r'\1', text)
    
    # Extract first date pattern
    match = re.search(r'\d{1,2}[-/ ]?[A-Za-z]{3,9}[-/ ]?\d{2,4}|\d{1,2}/\d{1,2}/\d{4}', text)
    
    if match:
        return match.group(0)
    else:
        return None

# Apply extraction
events_df["Clean_Date"] = events_df["Date"].apply(extract_first_date)

# Convert to datetime safely
events_df["Clean_Date"] = pd.to_datetime(
    events_df["Clean_Date"],
    dayfirst=True,
    errors="coerce"
)

events_df[["Date", "Clean_Date"]].head()

C:\Users\kerka\AppData\Local\Temp\ipykernel_32816\3885506640.py:25: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  events_df["Clean_Date"] = pd.to_datetime(

        Date Clean_Date
0  01-Jan-11 2011-01-01
1  15-Jan-11 2011-01-15
2  26-Jan-11 2011-01-26
3  16-Feb-11 2011-02-16
4  19-Feb-11 2011-02-19

In [7]:
## Removing null values
events_df["Clean_Date"].isna().sum()

3

In [8]:
events_df = events_df.dropna(subset=["Clean_Date"])

In [9]:
events_df["Clean_Date"].isna().sum()

0

In [10]:
## setting datetime as index

load_df = load_df.sort_values("DATETIME")

load_df.set_index("DATETIME", inplace=True)

load_df.head()

                       LOAD
DATETIME
2013-04-01 00:15:00  1136.0
2013-04-01 00:30:00  1111.0
2013-04-01 00:45:00  1081.0
2013-04-01 01:00:00  1050.0
2013-04-01 01:15:00  1023.0

In [11]:
load_df.index

DatetimeIndex(['2013-04-01 00:15:00', '2013-04-01 00:30:00',
               '2013-04-01 00:45:00', '2013-04-01 01:00:00',
               '2013-04-01 01:15:00', '2013-04-01 01:30:00',
               '2013-04-01 01:45:00', '2013-04-01 02:00:00',
               '2013-04-01 02:15:00', '2013-04-01 02:30:00',
               ...
               '2021-04-30 21:30:00', '2021-04-30 21:45:00',
               '2021-04-30 22:00:00', '2021-04-30 22:15:00',
               '2021-04-30 22:30:00', '2021-04-30 22:45:00',
               '2021-04-30 23:00:00', '2021-04-30 23:15:00',
               '2021-04-30 23:30:00', '2021-04-30 23:45:00'],
              dtype='datetime64[ns]', name='DATETIME', length=283391, freq=None)

In [12]:
## setting datetime as index

weather_df = weather_df.sort_values("DATETIME")

weather_df.set_index("DATETIME", inplace=True)

weather_df.head()

,ACT_HEAT_INDEX,ACT_HUMIDITY,ACT_RAIN,ACT_TEMP,COOL_FACTOR
DATETIME,,,,,
2013-04-01 00:15:00,26.289972,67.65,0.0,25.88,0.0
2013-04-01 00:30:00,26.145567,68.86,0.0,25.72,0.0
2013-04-01 00:45:00,26.048589,69.78,0.0,25.61,0.0
2013-04-01 01:00:00,25.938489,71.04,0.0,25.48,0.0
2013-04-01 01:15:00,25.891289,71.76,0.0,25.42,0.0

In [13]:
## sorting data by datetime

load_df = load_df.sort_index()

In [14]:
load_df.index.is_monotonic_increasing

True

In [15]:
## sorting data by datetime

events_df = events_df.sort_values("Clean_Date")

In [16]:
## checking for null values

print(load_df.isna().sum())
print(weather_df.isna().sum())

LOAD    0
dtype: int64
ACT_HEAT_INDEX    0
ACT_HUMIDITY      0
ACT_RAIN          0
ACT_TEMP          0
COOL_FACTOR       0
dtype: int64

In [17]:
## check for duplicate values

load_df.index.duplicated().sum()

0

In [18]:
weather_df.index.duplicated().sum()

0

In [19]:
## checking for constant time diffrence
load_df.index.to_series().diff().value_counts().head()

DATETIME
0 days 00:15:00    283390
Name: count, dtype: int64

In [20]:
## merging load_df and weather_df
master_df = load_df.join(weather_df, how="left")

In [21]:
master_df.shape

(283391, 6)

In [22]:
master_df.head()

,LOAD,ACT_HEAT_INDEX,ACT_HUMIDITY,ACT_RAIN,ACT_TEMP,COOL_FACTOR
DATETIME,,,,,,
2013-04-01 00:15:00,1136.0,26.289972,67.65,0.0,25.88,0.0
2013-04-01 00:30:00,1111.0,26.145567,68.86,0.0,25.72,0.0
2013-04-01 00:45:00,1081.0,26.048589,69.78,0.0,25.61,0.0
2013-04-01 01:00:00,1050.0,25.938489,71.04,0.0,25.48,0.0
2013-04-01 01:15:00,1023.0,25.891289,71.76,0.0,25.42,0.0

In [23]:
## extracting date column from datetime to merge event_df

master_df["DATE"] = master_df.index.date

In [24]:
master_df.head()

,LOAD,ACT_HEAT_INDEX,ACT_HUMIDITY,ACT_RAIN,ACT_TEMP,COOL_FACTOR,DATE
DATETIME,,,,,,,
2013-04-01 00:15:00,1136.0,26.289972,67.65,0.0,25.88,0.0,2013-04-01
2013-04-01 00:30:00,1111.0,26.145567,68.86,0.0,25.72,0.0,2013-04-01
2013-04-01 00:45:00,1081.0,26.048589,69.78,0.0,25.61,0.0,2013-04-01
2013-04-01 01:00:00,1050.0,25.938489,71.04,0.0,25.48,0.0,2013-04-01
2013-04-01 01:15:00,1023.0,25.891289,71.76,0.0,25.42,0.0,2013-04-01

In [25]:
events_df.head()

,Date,Event_Name,Holiday_Ind,Remarks,Clean_Date
0,01-Jan-11,New Year's Day,1,NaN,2011-01-01
1,15-Jan-11,Makar Sankranti,1,NaN,2011-01-15
2,26-Jan-11,Republic Day,1,NaN,2011-01-26
3,16-Feb-11,Id-e-Milad,1,NaN,2011-02-16
4,19-Feb-11,Chatrapati Shivaji Maharaj Jayanti,1,NaN,2011-02-19

In [26]:
events_df["Event_Date"] = events_df["Clean_Date"].dt.date

In [27]:
event_flag = events_df[["Event_Date"]].drop_duplicates()
event_flag["Is_Event"] = 1

In [28]:
master_df = master_df.merge(
    event_flag,
    left_on="DATE",
    right_on="Event_Date",
    how="left"
)

In [29]:
master_df["Is_Event"] = master_df["Is_Event"].fillna(0)

In [30]:
master_df.drop(columns=["Event_Date"], inplace=True)

In [31]:
master_df.isna().sum()

LOAD              0
ACT_HEAT_INDEX    0
ACT_HUMIDITY      0
ACT_RAIN          0
ACT_TEMP          0
COOL_FACTOR       0
DATE              0
Is_Event          0
dtype: int64

In [32]:
master_df.shape

(283391, 8)

In [33]:
master_df.head()

,LOAD,ACT_HEAT_INDEX,ACT_HUMIDITY,ACT_RAIN,ACT_TEMP,COOL_FACTOR,DATE,Is_Event
0,1136.0,26.289972,67.65,0.0,25.88,0.0,2013-04-01,0.0
1,1111.0,26.145567,68.86,0.0,25.72,0.0,2013-04-01,0.0
2,1081.0,26.048589,69.78,0.0,25.61,0.0,2013-04-01,0.0
3,1050.0,25.938489,71.04,0.0,25.48,0.0,2013-04-01,0.0
4,1023.0,25.891289,71.76,0.0,25.42,0.0,2013-04-01,0.0

In [34]:
master_df.columns

Index(['LOAD', 'ACT_HEAT_INDEX', 'ACT_HUMIDITY', 'ACT_RAIN', 'ACT_TEMP',
       'COOL_FACTOR', 'DATE', 'Is_Event'],
      dtype='object')

In [35]:
master_df.set_index(load_df.index, inplace=True)

In [36]:
master_df.head()

,LOAD,ACT_HEAT_INDEX,ACT_HUMIDITY,ACT_RAIN,ACT_TEMP,COOL_FACTOR,DATE,Is_Event
DATETIME,,,,,,,,
2013-04-01 00:15:00,1136.0,26.289972,67.65,0.0,25.88,0.0,2013-04-01,0.0
2013-04-01 00:30:00,1111.0,26.145567,68.86,0.0,25.72,0.0,2013-04-01,0.0
2013-04-01 00:45:00,1081.0,26.048589,69.78,0.0,25.61,0.0,2013-04-01,0.0
2013-04-01 01:00:00,1050.0,25.938489,71.04,0.0,25.48,0.0,2013-04-01,0.0
2013-04-01 01:15:00,1023.0,25.891289,71.76,0.0,25.42,0.0,2013-04-01,0.0

In [37]:
events_df.columns

Index(['Date', 'Event_Name', 'Holiday_Ind', 'Remarks', 'Clean_Date',
       'Event_Date'],
      dtype='object')

In [38]:
# Extract Hour
master_df["Hour"] = master_df.index.hour

# Day of Week (0 = Monday, 6 = Sunday)
master_df["Day_of_Week"] = master_df.index.dayofweek

# Month
master_df["Month"] = master_df.index.month

# Day of Year
master_df["Day_of_Year"] = master_df.index.dayofyear

# Is Weekend (Saturday=5, Sunday=6)
master_df["Is_Weekend"] = master_df["Day_of_Week"].isin([5, 6]).astype(int)

# Is Peak Hour (6 PM to 10 PM → 18 to 21)
master_df["Is_Peak_Hour"] = master_df["Hour"].between(18, 22).astype(int)

In [39]:
master_df[["Hour","Day_of_Week","Is_Weekend","Is_Peak_Hour"]].head(20)

                     Hour  Day_of_Week  Is_Weekend  Is_Peak_Hour
DATETIME
2013-04-01 00:15:00     0            0           0             0
2013-04-01 00:30:00     0            0           0             0
2013-04-01 00:45:00     0            0           0             0
2013-04-01 01:00:00     1            0           0             0
2013-04-01 01:15:00     1            0           0             0
2013-04-01 01:30:00     1            0           0             0
2013-04-01 01:45:00     1            0           0             0
2013-04-01 02:00:00     2            0           0             0
2013-04-01 02:15:00     2            0           0             0
2013-04-01 02:30:00     2            0           0             0
2013-04-01 02:45:00     2            0           0             0
2013-04-01 03:00:00     3            0           0             0
2013-04-01 03:15:00     3            0           0             0
2013-04-01 03:30:00     3            0           0             0
2013-04-01 03:45:00     3            0           0             0
2013-04-01 04:00:00     4            0           0             0
2013-04-01 04:15:00     4            0           0             0
2013-04-01 04:30:00     4            0           0             0
2013-04-01 04:45:00     4            0           0             0
2013-04-01 05:00:00     5            0           0             0

In [40]:
import numpy as np

# Hour Cyclical Encoding
master_df["Hour_sin"] = np.sin(2 * np.pi * master_df["Hour"] / 24)
master_df["Hour_cos"] = np.cos(2 * np.pi * master_df["Hour"] / 24)

master_df[["Hour", "Hour_sin", "Hour_cos"]].head()

                     Hour  Hour_sin  Hour_cos
DATETIME
2013-04-01 00:15:00     0  0.000000  1.000000
2013-04-01 00:30:00     0  0.000000  1.000000
2013-04-01 00:45:00     0  0.000000  1.000000
2013-04-01 01:00:00     1  0.258819  0.965926
2013-04-01 01:15:00     1  0.258819  0.965926

In [41]:
# 1-day lag (same time yesterday)
master_df["Load_lag_1day"] = master_df["LOAD"].shift(96)

# 7-day lag (same time last week)
master_df["Load_lag_7day"] = master_df["LOAD"].shift(672)

# Short-term memory
master_df["Load_lag_1"] = master_df["LOAD"].shift(1)
master_df["Load_lag_4"] = master_df["LOAD"].shift(4)

master_df[["LOAD", "Load_lag_1day", "Load_lag_7day"]].head(110)

                       LOAD  Load_lag_1day  Load_lag_7day
DATETIME
2013-04-01 00:15:00  1136.0            NaN            NaN
2013-04-01 00:30:00  1111.0            NaN            NaN
2013-04-01 00:45:00  1081.0            NaN            NaN
2013-04-01 01:00:00  1050.0            NaN            NaN
2013-04-01 01:15:00  1023.0            NaN            NaN
...                     ...            ...            ...
2013-04-02 02:30:00   933.0          919.0            NaN
2013-04-02 02:45:00   954.0          912.0            NaN
2013-04-02 03:00:00   920.0          903.0            NaN
2013-04-02 03:15:00   908.0          894.0            NaN
2013-04-02 03:30:00   913.0          883.0            NaN

[110 rows x 3 columns]

In [42]:
# 24-hour rolling mean (96 intervals)
master_df["Rolling_mean_24h"] = master_df["LOAD"].rolling(window=96).mean()

# 4-hour rolling mean (16 intervals)
master_df["Rolling_mean_4h"] = master_df["LOAD"].rolling(window=16).mean()

# 24-hour rolling standard deviation (volatility)
master_df["Rolling_std_24h"] = master_df["LOAD"].rolling(window=96).std()

master_df[["Rolling_mean_24h", "Rolling_std_24h"]].head(110)

                     Rolling_mean_24h  Rolling_std_24h
DATETIME
2013-04-01 00:15:00               NaN              NaN
2013-04-01 00:30:00               NaN              NaN
2013-04-01 00:45:00               NaN              NaN
2013-04-01 01:00:00               NaN              NaN
2013-04-01 01:15:00               NaN              NaN
...                               ...              ...
2013-04-02 02:30:00       1232.250000       224.367884
2013-04-02 02:45:00       1232.687500       223.777018
2013-04-02 03:00:00       1232.864583       223.519956
2013-04-02 03:15:00       1233.010417       223.301000
2013-04-02 03:30:00       1233.322917       222.826508

[110 rows x 2 columns]

In [43]:
master_df = master_df.dropna()

In [44]:
master_df.isna().sum()

LOAD                0
ACT_HEAT_INDEX      0
ACT_HUMIDITY        0
ACT_RAIN            0
ACT_TEMP            0
COOL_FACTOR         0
DATE                0
Is_Event            0
Hour                0
Day_of_Week         0
Month               0
Day_of_Year         0
Is_Weekend          0
Is_Peak_Hour        0
Hour_sin            0
Hour_cos            0
Load_lag_1day       0
Load_lag_7day       0
Load_lag_1          0
Load_lag_4          0
Rolling_mean_24h    0
Rolling_mean_4h     0
Rolling_std_24h     0
dtype: int64

In [45]:
# Define target
y = master_df["LOAD"]

# Drop target and unnecessary columns
X = master_df.drop(columns=["LOAD", "DATE"])

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

Feature shape: (282719, 21)
Target shape: (282719,)

In [46]:
# Train: 2013–2019
X_train = X.loc["2013":"2019"]
y_train = y.loc["2013":"2019"]

# Validation: 2020
X_val = X.loc["2020"]
y_val = y.loc["2020"]

# Test: 2021
X_test = X.loc["2021"]
y_test = y.loc["2021"]

print("Train shape:", X_train.shape)
print("Validation shape:", X_val.shape)
print("Test shape:", X_test.shape)

Train shape: (236063, 21)
Validation shape: (35136, 21)
Test shape: (11520, 21)

In [47]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit only on training data
X_train_scaled = scaler.fit_transform(X_train)

# Transform validation & test
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

In [48]:
import xgboost as xgb

xgb_model = xgb.XGBRegressor(
    objective='reg:squarederror',   # For baseline
    n_estimators=500,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

In [49]:
xgb_model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=500,
             n_jobs=None, num_parallel_tree=None, ...)

In [50]:
y_val_pred = xgb_model.predict(X_val)

In [51]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

mae = mean_absolute_error(y_val, y_val_pred)
rmse = np.sqrt(mean_squared_error(y_val, y_val_pred))

print("Validation MAE:", mae)
print("Validation RMSE:", rmse)

Validation MAE: 7.522427690919414
Validation RMSE: 11.827617163733068

In [52]:
print("MAE %:", (7.916880496429832 / y_val.mean()) * 100)

MAE %: 0.7243014436465774

In [53]:
def calculate_penalty(y_true, y_pred):
    penalty = 0
    
    for actual, forecast in zip(y_true, y_pred):
        if actual > forecast:
            penalty += (actual - forecast) * 4
        else:
            penalty += (forecast - actual) * 2
            
    return penalty

val_penalty = calculate_penalty(y_val.values, y_val_pred)

print("Validation Penalty:", val_penalty)

Validation Penalty: 762478.3712158203

In [54]:
best_penalty = float("inf")
best_shift = 0

for shift in range(-10, 21):  # try shifts from -10 to +20
    shifted_pred = y_val_pred + shift
    penalty = calculate_penalty(y_val.values, shifted_pred)
    
    if penalty < best_penalty:
        best_penalty = penalty
        best_shift = shift

print("Best Shift:", best_shift)
print("Best Penalty:", best_penalty)

Best Shift: 3
Best Penalty: 716643.9895019531

In [55]:
y_test_pred = xgb_model.predict(X_test)

In [56]:
y_test_pred_shifted = y_test_pred + 3

In [57]:
test_penalty = calculate_penalty(y_test.values, y_test_pred_shifted)

print("Test Penalty (after shift):", test_penalty)

Test Penalty (after shift): 200972.43464325852

In [58]:
master_df

,LOAD,ACT_HEAT_INDEX,ACT_HUMIDITY,ACT_RAIN,ACT_TEMP,COOL_FACTOR,DATE,Is_Event,Hour,Day_of_Week,...,Is_Peak_Hour,Hour_sin,Hour_cos,Load_lag_1day,Load_lag_7day,Load_lag_1,Load_lag_4,Rolling_mean_24h,Rolling_mean_4h,Rolling_std_24h
DATETIME,,,,,,,,,,,,,,,,,,,,,
2013-04-08 00:15:00,1181.000000,25.990906,73.89,0.0,25.46,0.00,2013-04-08,0.0,0,0,...,0,0.000000,1.000000,1225.000000,1136.000000,1203.000000,1250.000000,1088.552083,1251.500000,123.592784
2013-04-08 00:30:00,1163.000000,25.851006,74.43,0.0,25.32,0.00,2013-04-08,0.0,0,0,...,0,0.000000,1.000000,1206.000000,1111.000000,1181.000000,1241.000000,1088.104167,1245.125000,123.240072
2013-04-08 00:45:00,1127.000000,25.695078,75.62,0.0,25.15,0.00,2013-04-08,0.0,0,0,...,0,0.000000,1.000000,1175.000000,1081.000000,1163.000000,1229.000000,1087.604167,1236.437500,122.980912
2013-04-08 01:00:00,1086.000000,25.424450,76.63,0.0,24.88,0.00,2013-04-08,0.0,1,0,...,0,0.258819,0.965926,1135.000000,1050.000000,1127.000000,1203.000000,1087.093750,1225.000000,122.883777
2013-04-08 01:15:00,1054.000000,25.189989,77.34,0.0,24.65,0.00,2013-04-08,0.0,1,0,...,0,0.258819,0.965926,1101.000000,1023.000000,1086.000000,1181.000000,1086.604167,1211.625000,122.921411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-30 22:45:00,1428.735652,38.457513,80.89,0.0,30.17,3.17,2021-04-30,0.0,22,4,...,1,-0.500000,0.866025,1485.172452,1346.331980,1406.345944,1365.324180,1328.793528,1344.693549,120.760404
2021-04-30 23:00:00,1449.918164,37.972995,80.42,0.0,30.06,3.06,2021-04-30,0.0,23,4,...,0,-0.258819,0.965926,1511.323948,1365.250556,1428.735652,1375.667852,1328.153885,1356.527147,119.943262
2021-04-30 23:15:00,1466.729480,37.003949,78.05,0.0,29.96,2.96,2021-04-30,0.0,23,4,...,0,-0.258819,0.965926,1537.689312,1385.889352,1449.918164,1390.014672,1327.414720,1368.112733,118.852068
2021-04-30 23:30:00,1486.805772,36.567804,77.18,0.0,29.89,2.89,2021-04-30,0.0,23,4,...,0,-0.258819,0.965926,1552.809500,1409.839464,1466.729480,1406.345944,1326.727181,1379.317946,117.719991
2021-04-30 23:45:00,1494.982516,36.730966,77.47,0.0,29.92,2.92,2021-04-30,0.0,23,4,...,0,-0.258819,0.965926,1554.944200,1412.028632,1486.805772,1428.735652,1326.102580,1389.837603,116.650582

In [59]:
# Company forecast = lag 1 day
baseline_val_pred = X_val["Load_lag_1day"]

baseline_val_penalty = calculate_penalty(y_val.values, baseline_val_pred.values)

print("Baseline Validation Penalty:", baseline_val_penalty)

Baseline Validation Penalty: 5490968.0

In [60]:
baseline_test_pred = X_test["Load_lag_1day"]

baseline_test_penalty = calculate_penalty(y_test.values, baseline_test_pred.values)

print("Baseline Test Penalty:", baseline_test_penalty)

Baseline Test Penalty: 2030777.878206

In [61]:
val_savings = baseline_val_penalty - best_penalty
val_percent = (val_savings / baseline_val_penalty) * 100

print("Validation Savings ₹:", val_savings)
print("Validation % Reduction:", val_percent)

Validation Savings ₹: 4774324.010498047
Validation % Reduction: 86.94867663585086

In [62]:
test_savings = baseline_test_penalty - test_penalty
test_percent = (test_savings / baseline_test_penalty) * 100

print("Test Savings ₹:", test_savings)
print("Test % Reduction:", test_percent)

Test Savings ₹: 1829805.4435627414
Test % Reduction: 90.10367225288081

In [63]:
peak_mask = X_val["Is_Peak_Hour"] == 1
peak_penalty = calculate_penalty(
    y_val[peak_mask].values,
    (y_val_pred + 3)[peak_mask]
)
peak_penalty

184458.12634277344

In [64]:
offpeak_mask = X_val["Is_Peak_Hour"] == 0
offpeak_penalty = calculate_penalty(
    y_val[offpeak_mask].values,
    (y_val_pred + 3)[offpeak_mask]
)
offpeak_penalty

532185.8631591797

In [65]:
bias = ((y_val_pred + 3) - y_val).mean() / y_val.mean() * 100

In [66]:
bias

0.35374016115468754

In [67]:
import numpy as np
abs_error = np.abs((y_val_pred + 3) - y_val)
p95 = np.percentile(abs_error, 95)

In [68]:
p95

21.413406372070312

In [69]:
abs_error

DATETIME
2020-01-01 00:00:00     1.057129
2020-01-01 00:15:00     1.118164
2020-01-01 00:30:00     3.315063
2020-01-01 00:45:00     4.435547
2020-01-01 01:00:00     2.330200
                         ...
2020-12-31 22:45:00     1.275940
2020-12-31 23:00:00     1.969421
2020-12-31 23:15:00     4.223755
2020-12-31 23:30:00    14.456482
2020-12-31 23:45:00    12.810730
Name: LOAD, Length: 35136, dtype: float64

In [71]:
load_test = pd.read_csv("Electric_Load_Data_Test.csv")
weather_test = pd.read_csv("External_Factor_Data_Test.csv")

In [72]:
## Converting Datetime to standard format

load_test["DATETIME"] = pd.to_datetime(
    load_test["DATETIME"],
    format="%d%b%Y:%H:%M:%S"
)

In [81]:
## Converting Datetime to standard format

weather_test["DATETIME"] = pd.to_datetime(
    weather_test["DATETIME"],
    format="%d%b%Y:%H:%M:%S"
)

weather_test.dtypes

DATETIME          datetime64[ns]
ACT_HEAT_INDEX           float64
ACT_HUMIDITY             float64
ACT_RAIN                   int64
ACT_TEMP                 float64
COOL_FACTOR              float64
dtype: object

In [82]:
## setting datetime as index

load_test = load_test.sort_values("DATETIME")

load_test.set_index("DATETIME", inplace=True)

load_test.head()

KeyError: "None of ['DATETIME'] are in the columns"

In [83]:
load_test.index.is_monotonic_increasing

True

In [84]:
## merging load_df and weather_df
master_test = load_test.join(weather_test, how="left")

In [93]:
master_test = master_test.drop("DATETIME", axis = 1)

In [99]:
master_test.index = load_test.index

In [100]:
master_test.index

DatetimeIndex(['2021-05-01 00:00:00', '2021-05-01 00:15:00',
               '2021-05-01 00:30:00', '2021-05-01 00:45:00',
               '2021-05-01 01:00:00', '2021-05-01 01:15:00',
               '2021-05-01 01:30:00', '2021-05-01 01:45:00',
               '2021-05-01 02:00:00', '2021-05-01 02:15:00',
               ...
               '2021-05-31 21:45:00', '2021-05-31 22:00:00',
               '2021-05-31 22:15:00', '2021-05-31 22:30:00',
               '2021-05-31 22:45:00', '2021-05-31 23:00:00',
               '2021-05-31 23:15:00', '2021-05-31 23:30:00',
               '2021-05-31 23:45:00', '2021-06-01 00:00:00'],
              dtype='datetime64[ns]', name='DATETIME', length=2977, freq=None)

In [101]:
## extracting date column from datetime to merge event_df

master_test["DATE"] = master_test.index.date

In [102]:
master_test = master_test.merge(
    event_flag,
    left_on="DATE",
    right_on="Event_Date",
    how="left"
)

In [103]:
master_test["Is_Event"] = master_test["Is_Event"].fillna(0)

In [104]:
master_test.drop(columns=["Event_Date"], inplace=True)

LOAD                 0
ACT_HEAT_INDEX    2977
ACT_HUMIDITY      2977
ACT_RAIN          2977
ACT_TEMP          2977
COOL_FACTOR       2977
DATE                 0
Is_Event             0
dtype: int64

In [155]:
def calculate_stage2_penalty(y_true, y_pred, datetime_index):
    
    penalty = 0
    peak_penalty = 0
    offpeak_penalty = 0
    
    for actual, forecast, dt in zip(y_true, y_pred, datetime_index):
        
        hour = dt.hour
        is_peak = (hour >= 18) and (hour < 22)
        
        if actual > forecast:  # Under-forecast
            
            if is_peak:
                cost = (actual - forecast) * 6
            else:
                cost = (actual - forecast) * 4
                
        else:  # Over-forecast
            cost = (forecast - actual) * 2
        
        penalty += cost
        
        if is_peak:
            peak_penalty += cost
        else:
            offpeak_penalty += cost
            
    return penalty, peak_penalty, offpeak_penalty

In [156]:
total2, peak2, off2 = calculate_stage2_penalty(
    load_test["LOAD"].values,
    y_test_pred,
    load_test.index
)

print("Stage 2 Total Penalty:", total2)
print("Stage 2 Peak Penalty:", peak2)
print("Stage 2 Off-Peak Penalty:", off2)

Stage 2 Total Penalty: 3575785.6045796666
Stage 2 Peak Penalty: 440085.25224664866
Stage 2 Off-Peak Penalty: 3135700.3523330153

In [188]:
print("Length of base_pred:", len(base_pred))
print("Length of actual LOAD:", len(load_test["LOAD"]))

Length of base_pred: 11520
Length of actual LOAD: 2977

In [186]:
bias = ((final_pred - load_test["LOAD"]).mean() /
        load_test["LOAD"].mean()) * 100

print("Stage 3 Bias (%):", bias)

Stage 3 Bias (%): -21.83963092482839